### ISSUE TITLE
RubyNLP

### ISSUE THREAD

**Issue by arbox** [abitdodgy/words_counted#26]
Dear Mohamad,

I've recently added your project to our RubyNLP list: https://github.com/arbox/nlp-with-ruby

I wonder if you want to participate in the Ruby for NLP network. You could do this in a very simple step by adding the `rubynlp` topic to your GitHub repository. You may want to spread a word on Twitter or on other media :)

Thank you for the project!

**Comment by abitdodgy** [comment]
@arbox done. Thanks for spreading the word!

**Comment by arbox** [comment]
You're welcome! Use the list, make it useful for others! Thank you for your project and contributions!
